resolver: lts-7.7

packages:
- ./
- location:
    git: https://github.com/vfiles/aeson-versioned
    commit: 3a05ffafef26cf96e627fd64e247726307f9263a
  extra-dep: true

extra-deps:
- clock-0.7.2
- snap-1.0.0.1
- heist-1.0.1.0
- map-syntax-0.2.0.1
